In [50]:
import pandas as pd

df = pd.DataFrame({
    "Student Name": [
        "Avi",
        "Neha",
        "Rahul",
        "Riya",
        "John",
        "Sara",
        "Aman",
        "Priya",
        "Karan",
        "Meera"
    ],

    "City": [
        "Delhi",
        "delhi",
        "DELHI",
        "Mumbai",
        "mumbai",
        "MUMBAI",
        "New York",
        "NY",
        "N.Y.",
        "new york"
    ],

    "Gender": [
        "Male",
        "male",
        "MALE",
        "Female",
        "female",
        "FEMALE",
        "Male",
        "Female",
        "male",
        "FEMALE"
    ],

    "Price": [
        "45000",
        "52000",
        "61000",
        "47000",
        "55000",
        "68000",
        "49000",
        "51000",
        "53000",
        "62000"
    ],

    "Mileage(mpg)": [
        30,
        28,
        35,
        32,
        31,
        29,
        34,
        33,
        36,
        27
    ]
})

df

  Student Name      City  Gender  Price  Mileage(mpg)
0          Avi     Delhi    Male  45000            30
1         Neha     delhi    male  52000            28
2        Rahul     DELHI    MALE  61000            35
3         Riya    Mumbai  Female  47000            32
4         John    mumbai  female  55000            31
5         Sara    MUMBAI  FEMALE  68000            29
6         Aman  New York    Male  49000            34
7        Priya        NY  Female  51000            33
8        Karan      N.Y.    male  53000            36
9        Meera  new york  FEMALE  62000            27

### Explore the Dataset

**Display the dataset.**

In [51]:
print(df)

  Student Name      City  Gender  Price  Mileage(mpg)
0          Avi     Delhi    Male  45000            30
1         Neha     delhi    male  52000            28
2        Rahul     DELHI    MALE  61000            35
3         Riya    Mumbai  Female  47000            32
4         John    mumbai  female  55000            31
5         Sara    MUMBAI  FEMALE  68000            29
6         Aman  New York    Male  49000            34
7        Priya        NY  Female  51000            33
8        Karan      N.Y.    male  53000            36
9        Meera  new york  FEMALE  62000            27

**Display the first 5 rows.**

In [52]:
print(df.head())

  Student Name    City  Gender  Price  Mileage(mpg)
0          Avi   Delhi    Male  45000            30
1         Neha   delhi    male  52000            28
2        Rahul   DELHI    MALE  61000            35
3         Riya  Mumbai  Female  47000            32
4         John  mumbai  female  55000            31

**Display the last 3 rows.**

In [53]:
print(df.tail())

  Student Name      City  Gender  Price  Mileage(mpg)
5         Sara    MUMBAI  FEMALE  68000            29
6         Aman  New York    Male  49000            34
7        Priya        NY  Female  51000            33
8        Karan      N.Y.    male  53000            36
9        Meera  new york  FEMALE  62000            27

**Find the shape.**

In [54]:
print(df.shape)

(10, 5)

**Display column names.**

In [55]:
df.columns

Index(['Student Name', 'City', 'Gender', 'Price', 'Mileage(mpg)'], dtype='object')

**Check data types using dtypes.**

In [56]:
df.dtypes

Student Name    object
City            object
Gender          object
Price           object
Mileage(mpg)     int64
dtype: object

**Display basic information using info().**

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  10 non-null     object
 1   City          10 non-null     object
 2   Gender        10 non-null     object
 3   Price         10 non-null     object
 4   Mileage(mpg)  10 non-null     int64
dtypes: int64(1), object(4)
memory usage: 532.0+ bytes

### Text Formatting

**Convert every city name to lowercase.**

In [58]:
df.City = df.City.str.lower()

**Convert Gender into title case.**

In [59]:
df.Gender= df.Gender.str.title()

**Count unique city names before cleaning.**

In [60]:
df.City.nunique()

5

**Standardize**
- NY
- N.Y.
- new york

into

- New York

In [61]:
df.City = df.City.replace(["new york", "n.y.","ny"],"New York" )

**Count unique cities again.**

In [62]:
df.City.nunique()

3

**Data Types**

**Check the data type of Price.**

In [63]:
df["Price"].dtypes

dtype('O')

**Convert Price from object to integer.**

In [64]:
df["Price"] =pd.to_numeric(df["Price"])
df["Price"]

0    45000
1    52000
2    61000
3    47000
4    55000
5    68000
6    49000
7    51000
8    53000
9    62000
Name: Price, dtype: int64

**Verify the conversion.**

In [65]:
df["Price"].dtypes

dtype('int64')

**Calculate**
* Mean Price
* Maximum Price
* Minimum Price

In [66]:
print(df["Price"].mean())
print(df["Price"].max())
print(df["Price"].min())

54300.0
68000
45000

**Unit Conversion**

**Convert Mileage(mpg) to Mileage(L/100km)**

In [67]:
df["Mileage(L/100km)"]=round(235 / df["Mileage(mpg)"],2)

In [68]:
df["Mileage(L/100km)"]

0    7.83
1    8.39
2    6.71
3    7.34
4    7.58
5    8.10
6    6.91
7    7.12
8    6.53
9    8.70
Name: Mileage(L/100km), dtype: float64

### Rename Columns

**Rename Student Name --> Student**

In [70]:
df.rename(columns={"Student Name": "Student"})

  Student      City  Gender  Price  Mileage(mpg)  Mileage(L/100km)
0     Avi     delhi    Male  45000            30              7.83
1    Neha     delhi    Male  52000            28              8.39
2   Rahul     delhi    Male  61000            35              6.71
3    Riya    mumbai  Female  47000            32              7.34
4    John    mumbai  Female  55000            31              7.58
5    Sara    mumbai  Female  68000            29              8.10
6    Aman  New York    Male  49000            34              6.91
7   Priya  New York  Female  51000            33              7.12
8   Karan  New York    Male  53000            36              6.53
9   Meera  New York  Female  62000            27              8.70

**Rename Mileage(mpg) --> Mileage_MPG**

In [74]:
df.rename(columns={"Mileage(mpg)":"Mileage_MPG"})

  Student Name      City  Gender  Price  Mileage_MPG  Mileage(L/100km)
0          Avi     delhi    Male  45000           30              7.83
1         Neha     delhi    Male  52000           28              8.39
2        Rahul     delhi    Male  61000           35              6.71
3         Riya    mumbai  Female  47000           32              7.34
4         John    mumbai  Female  55000           31              7.58
5         Sara    mumbai  Female  68000           29              8.10
6         Aman  New York    Male  49000           34              6.91
7        Priya  New York  Female  51000           33              7.12
8        Karan  New York    Male  53000           36              6.53
9        Meera  New York  Female  62000           27              8.70

**Rename Price --> Selling_Price**

In [72]:
df.rename(columns={"Price":"Selling_Price"})

,Student Name,City,Gender,Selling_Price,Mileage(mpg),Mileage(L/100km)
0,Avi,delhi,Male,45000,30,7.83
1,Neha,delhi,Male,52000,28,8.39
2,Rahul,delhi,Male,61000,35,6.71
3,Riya,mumbai,Female,47000,32,7.34
4,John,mumbai,Female,55000,31,7.58
5,Sara,mumbai,Female,68000,29,8.10
6,Aman,New York,Male,49000,34,6.91
7,Priya,New York,Female,51000,33,7.12
8,Karan,New York,Male,53000,36,6.53
9,Meera,New York,Female,62000,27,8.70

In [73]:
df

  Student Name      City  Gender  Price  Mileage(mpg)  Mileage(L/100km)
0          Avi     delhi    Male  45000            30              7.83
1         Neha     delhi    Male  52000            28              8.39
2        Rahul     delhi    Male  61000            35              6.71
3         Riya    mumbai  Female  47000            32              7.34
4         John    mumbai  Female  55000            31              7.58
5         Sara    mumbai  Female  68000            29              8.10
6         Aman  New York    Male  49000            34              6.91
7        Priya  New York  Female  51000            33              7.12
8        Karan  New York    Male  53000            36              6.53
9        Meera  New York  Female  62000            27              8.70