In [93]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student": ["Avi", "Neha", "Rahul", "Riya", "John",
                "Sara", "Aman", "Priya", "Karan", "Meera"],

    "Age": [22, np.nan, 24, 23, np.nan,
            21, 22, np.nan, 24, 23],

    "Gender": ["Male", "Female", np.nan, "Female", "Male",
               "Female", "Male", np.nan, "Male", "Female"],

    "Marks": [88, 91, np.nan, 79, 85,
              np.nan, 92, 87, np.nan, 90],

    "City": ["Delhi", "Mumbai", "Delhi", np.nan, "Pune",
             "Delhi", "Mumbai", "Pune", np.nan, "Delhi"],

    "Salary": [45000, 52000, np.nan, 48000, 51000,
               np.nan, 56000, 49000, 47000, np.nan]
})

df

  Student   Age  Gender  Marks    City   Salary
0     Avi  22.0    Male   88.0   Delhi  45000.0
1    Neha   NaN  Female   91.0  Mumbai  52000.0
2   Rahul  24.0     NaN    NaN   Delhi      NaN
3    Riya  23.0  Female   79.0     NaN  48000.0
4    John   NaN    Male   85.0    Pune  51000.0
5    Sara  21.0  Female    NaN   Delhi      NaN
6    Aman  22.0    Male   92.0  Mumbai  56000.0
7   Priya   NaN     NaN   87.0    Pune  49000.0
8   Karan  24.0    Male    NaN     NaN  47000.0
9   Meera  23.0  Female   90.0   Delhi      NaN

### Detect Missing Values

**Display the dataset.**

In [94]:
df.head()

  Student   Age  Gender  Marks    City   Salary
0     Avi  22.0    Male   88.0   Delhi  45000.0
1    Neha   NaN  Female   91.0  Mumbai  52000.0
2   Rahul  24.0     NaN    NaN   Delhi      NaN
3    Riya  23.0  Female   79.0     NaN  48000.0
4    John   NaN    Male   85.0    Pune  51000.0

**Check if there are any missing values.**

In [95]:
df.isnull().values.any()

np.True_

**Count missing values in each column**

In [96]:
df.isna().sum()

Student    0
Age        3
Gender     2
Marks      3
City       2
Salary     3
dtype: int64

**Count total missing values**

In [97]:
df.isna().sum().sum()

np.int64(13)

**Find the percentage of missing values in each column.**

In [98]:
df.isna().mean() *100

Student     0.0
Age        30.0
Gender     20.0
Marks      30.0
City       20.0
Salary     30.0
dtype: float64

**Show only rows containing at least one missing value.**

In [99]:
df[df.isna().any(axis=1)]

  Student   Age  Gender  Marks    City   Salary
1    Neha   NaN  Female   91.0  Mumbai  52000.0
2   Rahul  24.0     NaN    NaN   Delhi      NaN
3    Riya  23.0  Female   79.0     NaN  48000.0
4    John   NaN    Male   85.0    Pune  51000.0
5    Sara  21.0  Female    NaN   Delhi      NaN
7   Priya   NaN     NaN   87.0    Pune  49000.0
8   Karan  24.0    Male    NaN     NaN  47000.0
9   Meera  23.0  Female   90.0   Delhi      NaN

**Show rows with no missing values.**

In [100]:
df[df.notnull().all(axis=1)]

  Student   Age Gender  Marks    City   Salary
0     Avi  22.0   Male   88.0   Delhi  45000.0
6    Aman  22.0   Male   92.0  Mumbai  56000.0

### Drop Missing Values

**Drop every row containing at least one missing value**

In [101]:
df.dropna(axis=0)

  Student   Age Gender  Marks    City   Salary
0     Avi  22.0   Male   88.0   Delhi  45000.0
6    Aman  22.0   Male   92.0  Mumbai  56000.0

**Drop every column containing at least one missing value.**

In [102]:
df.dropna(axis=1)

  Student
0     Avi
1    Neha
2   Rahul
3    Riya
4    John
5    Sara
6    Aman
7   Priya
8   Karan
9   Meera

**Drop rows only if all values are missing.**

In [103]:
df.dropna(how="all")

  Student   Age  Gender  Marks    City   Salary
0     Avi  22.0    Male   88.0   Delhi  45000.0
1    Neha   NaN  Female   91.0  Mumbai  52000.0
2   Rahul  24.0     NaN    NaN   Delhi      NaN
3    Riya  23.0  Female   79.0     NaN  48000.0
4    John   NaN    Male   85.0    Pune  51000.0
5    Sara  21.0  Female    NaN   Delhi      NaN
6    Aman  22.0    Male   92.0  Mumbai  56000.0
7   Priya   NaN     NaN   87.0    Pune  49000.0
8   Karan  24.0    Male    NaN     NaN  47000.0
9   Meera  23.0  Female   90.0   Delhi      NaN

**Keep only rows having at least 4 non-null values**

In [104]:
df.dropna(thresh=4)

  Student   Age  Gender  Marks    City   Salary
0     Avi  22.0    Male   88.0   Delhi  45000.0
1    Neha   NaN  Female   91.0  Mumbai  52000.0
3    Riya  23.0  Female   79.0     NaN  48000.0
4    John   NaN    Male   85.0    Pune  51000.0
5    Sara  21.0  Female    NaN   Delhi      NaN
6    Aman  22.0    Male   92.0  Mumbai  56000.0
7   Priya   NaN     NaN   87.0    Pune  49000.0
8   Karan  24.0    Male    NaN     NaN  47000.0
9   Meera  23.0  Female   90.0   Delhi      NaN

**Drop columns having more than 2 missing values**

In [105]:
df.dropna(axis=1, thresh = len(df)-2)

  Student  Gender    City
0     Avi    Male   Delhi
1    Neha  Female  Mumbai
2   Rahul     NaN   Delhi
3    Riya  Female     NaN
4    John    Male    Pune
5    Sara  Female   Delhi
6    Aman    Male  Mumbai
7   Priya     NaN    Pune
8   Karan    Male     NaN
9   Meera  Female   Delhi

### Replace Missing Values

**Replace missing Age with mean.**

In [106]:
import numpy as np

In [107]:
mean= df["Age"].mean()
print(mean)
df["Age"].replace(np.nan, mean)

22.714285714285715

0    22.000000
1    22.714286
2    24.000000
3    23.000000
4    22.714286
5    21.000000
6    22.000000
7    22.714286
8    24.000000
9    23.000000
Name: Age, dtype: float64

**Replace missing Marks with median.**

In [108]:
median = df["Marks"].median()
df["Marks"].replace(np.nan,median)

0    88.0
1    91.0
2    88.0
3    79.0
4    85.0
5    88.0
6    92.0
7    87.0
8    88.0
9    90.0
Name: Marks, dtype: float64

**Replace missing Salary with mean.**

In [109]:
mean_salary = df["Salary"].mean()
print(mean_salary)
df["Salary"].replace(np.nan, mean_salary)

49714.28571428572

0    45000.000000
1    52000.000000
2    49714.285714
3    48000.000000
4    51000.000000
5    49714.285714
6    56000.000000
7    49000.000000
8    47000.000000
9    49714.285714
Name: Salary, dtype: float64

**Replace missing Gender with mode.**

In [110]:
mode = df["Gender"].mode()[0]
df["Gender"].replace(np.nan, mode)

0      Male
1    Female
2    Female
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
Name: Gender, dtype: object

**Replace missing City with mode.**

In [111]:
mode= df["City"].mode()[0]
df["City"].fillna(mode)

0     Delhi
1    Mumbai
2     Delhi
3     Delhi
4      Pune
5     Delhi
6    Mumbai
7      Pune
8     Delhi
9     Delhi
Name: City, dtype: object

**Replace every NaN with "Unknown".**

In [112]:
df.replace(np.nan,"Unknown")

  Student      Age   Gender    Marks     City   Salary
0     Avi     22.0     Male     88.0    Delhi  45000.0
1    Neha  Unknown   Female     91.0   Mumbai  52000.0
2   Rahul     24.0  Unknown  Unknown    Delhi  Unknown
3    Riya     23.0   Female     79.0  Unknown  48000.0
4    John  Unknown     Male     85.0     Pune  51000.0
5    Sara     21.0   Female  Unknown    Delhi  Unknown
6    Aman     22.0     Male     92.0   Mumbai  56000.0
7   Priya  Unknown  Unknown     87.0     Pune  49000.0
8   Karan     24.0     Male  Unknown  Unknown  47000.0
9   Meera     23.0   Female     90.0    Delhi  Unknown

**Replace only Salary NaNs with 0.**

In [113]:
df["Salary"].fillna(0)

0    45000.0
1    52000.0
2        0.0
3    48000.0
4    51000.0
5        0.0
6    56000.0
7    49000.0
8    47000.0
9        0.0
Name: Salary, dtype: float64

**Replace Age NaNs using forward fill.**

In [114]:
df["Age"].ffill()

0    22.0
1    22.0
2    24.0
3    23.0
4    23.0
5    21.0
6    22.0
7    22.0
8    24.0
9    23.0
Name: Age, dtype: float64

**Replace Marks NaNs using backward fill**

In [115]:
df["Marks"].bfill()

0    88.0
1    91.0
2    79.0
3    79.0
4    85.0
5    92.0
6    92.0
7    87.0
8    90.0
9    90.0
Name: Marks, dtype: float64

### Analysis

**Which column has the most missing values?**

In [116]:
df.isna().sum().idxmax()

'Age'

**Which row has the most missing values?**

In [117]:
df.isna().sum(axis=1).idxmax()

2

**Calculate average salary after filling missing values.**

In [121]:
print(df["Salary"].fillna(df["Salary"].mean()).mean())

49714.28571428572

**Calculate average marks after filling missing values.**

In [125]:
print(df["Marks"].fillna(df["Marks"].mean()).mean())

87.42857142857143

**Count missing values by data type.**

In [126]:
df

  Student   Age  Gender  Marks    City   Salary
0     Avi  22.0    Male   88.0   Delhi  45000.0
1    Neha   NaN  Female   91.0  Mumbai  52000.0
2   Rahul  24.0     NaN    NaN   Delhi      NaN
3    Riya  23.0  Female   79.0     NaN  48000.0
4    John   NaN    Male   85.0    Pune  51000.0
5    Sara  21.0  Female    NaN   Delhi      NaN
6    Aman  22.0    Male   92.0  Mumbai  56000.0
7   Priya   NaN     NaN   87.0    Pune  49000.0
8   Karan  24.0    Male    NaN     NaN  47000.0
9   Meera  23.0  Female   90.0   Delhi      NaN

**Count missing values by data type.**

In [127]:
df.isna().sum().groupby(df.dtypes).sum()

float64    9
object     4
dtype: int64