### DataFrame

In [75]:
import pandas as pd

In [76]:
record1 = pd.Series({
    "Name" : "Alice",
    "class" : "Physics",
    "Score" : 85
})
record2 = pd.Series({
    "Name" : "Jack",
    "class" : "Chemistry",
    "Score" : 82
})
record3 = pd.Series({
    "Name" : "Helen",
    "class" : "Biology",
    "Score" : 90
})

**Create datafram**

In [77]:
df =pd.DataFrame([record1,record2,record2],
                 index=["school1","school2","school1"])

In [78]:
df.head()

          Name      class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1   Jack  Chemistry     82

**Another way to create dataframe**

In [79]:
students= [{
    "Name" : "Alice",
    "class" : "Physics",
    "Score" : 85},
    {
    "Name" : "Jack",
    "class" : "Chemistry",
    "Score" : 82
    },
    {
    "Name" : "Helen",
    "class" : "Biology",
    "Score" : 90   
    }

]

df =pd.DataFrame(students,index=["school1","school2","school1"])

In [80]:
df

          Name      class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

**extract value from dataframe**

In [81]:
df.loc["school2"]

Name          Jack
class    Chemistry
Score           82
Name: school2, dtype: object

In [82]:
type(df.loc["school2"])

pandas.core.series.Series

In [83]:
df.loc["school1"]

          Name    class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [84]:
type(df.loc["school1"])

pandas.core.frame.DataFrame

**Extract rows and column together**

In [85]:
df.loc["school1","Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

**Transpose dataframe**

In [86]:
df.T

       school1    school2  school1
Name     Alice       Jack    Helen
class  Physics  Chemistry  Biology
Score       85         82       90

In [87]:
df.T.loc["Name"]

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [88]:
df["Name"]

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [89]:
df

          Name      class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [90]:
df.loc["Name"]

KeyError: 'Name'

In [ ]:
type(df["Name"])

pandas.core.series.Series

In [ ]:
df.loc["school1"]["Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

In [ ]:
print(type(df.loc["school1"]))
print(type(df.loc["school1"]["Name"]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [ ]:
df.loc[:,['Name',"Score"]]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

**Delete rows**

In [ ]:
df.drop("school1")

         Name      class  Score
school2  Jack  Chemistry     82

In [ ]:
df

          Name      class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

* axis = 0 --> rows
* axis= 1 --> columns

In [ ]:
copy_df = df.copy()
copy_df

          Name      class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [ ]:
copy_df.drop("Name", axis=1, inplace=True)
copy_df

             class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [91]:
del copy_df["class"]
copy_df

         Score
school1     85
school2     82
school1     90

**add columns**

In [92]:
df

          Name      class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [93]:
df["ClassRanking"] = None
df

          Name      class  Score ClassRanking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     90         None