In [1]:
import pandas as pd

students = {
    "Name": ["Avi", "Rahul", "Priya", "Ankit", "Sara"],
    "Age": [21, 22, 20, 23, 21],
    "Marks": [85, 67, 90, 45, 78],
    "City": ["Patna", "Delhi", "Mumbai", "Patna", "Delhi"]
}

df = pd.DataFrame(students)

**Print the first 3 rows.**

In [2]:
df.head(3)

    Name  Age  Marks    City
0    Avi   21     85   Patna
1  Rahul   22     67   Delhi
2  Priya   20     90  Mumbai

**Print the last 2 rows.**

In [7]:
df.tail(2)

    Name  Age  Marks   City
3  Ankit   23     45  Patna
4   Sara   21     78  Delhi

**Display only the Name column.**

In [9]:
df["Name"]

0      Avi
1    Rahul
2    Priya
3    Ankit
4     Sara
Name: Name, dtype: object

**Display Name and Marks columns.**

In [5]:
df[["Name","Marks"]]

    Name  Marks
0    Avi     85
1  Rahul     67
2  Priya     90
3  Ankit     45
4   Sara     78

**Print the shape of the DataFrame.**

In [6]:
df.shape

(5, 4)

**Print all column names.**

In [8]:
df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='object')

**Print the data types of each column.**

In [10]:
df.dtypes

Name     object
Age       int64
Marks     int64
City     object
dtype: object

**Display only students whose marks are greater than 70.**

In [25]:
marks_filt = df["Marks"] > 70
df.loc[marks_filt]

    Name  Age  Marks    City
0    Avi   21     85   Patna
2  Priya   20     90  Mumbai
4   Sara   21     78   Delhi

**Display students whose city is Patna.**

In [23]:
df.loc[df["City"] =="Patna"]

    Name  Age  Marks   City
0    Avi   21     85  Patna
3  Ankit   23     45  Patna

**Display students whose age is greater than 21.**

In [24]:
df.loc[df["Age"] > 21]

    Name  Age  Marks   City
1  Rahul   22     67  Delhi
3  Ankit   23     45  Patna

**Print the second row using .iloc.**

In [26]:
df.iloc[1]

Name     Rahul
Age         22
Marks       67
City     Delhi
Name: 1, dtype: object

**Print rows 2 to 4 (inclusive).**

In [27]:
df.iloc[2:4]

    Name  Age  Marks    City
2  Priya   20     90  Mumbai
3  Ankit   23     45   Patna

**Print the Name and City columns for the first three rows.**

In [28]:
df[["Name","City"]].head(3)

    Name    City
0    Avi   Patna
1  Rahul   Delhi
2  Priya  Mumbai

**Increase everyone's marks by 5.**

In [31]:
df["Marks"]=df["Marks"] + 5

**Create a new column called Percentage.**

In [32]:
df["Percentage"] = df["Marks"] /100
df

    Name  Age  Marks    City  Percentage
0    Avi   21     90   Patna        0.90
1  Rahul   22     72   Delhi        0.72
2  Priya   20     95  Mumbai        0.95
3  Ankit   23     50   Patna        0.50
4   Sara   21     83   Delhi        0.83

**Create a new column called Pass.**

Condition:

Marks >= 50 → True
Marks < 50 → False

In [34]:
def grade(Marks):
    if Marks >=50:
        return True
    else:
        return False
    
df["Pass"]= df["Marks"].apply(grade)

In [35]:
df

    Name  Age  Marks    City  Percentage  Pass
0    Avi   21     90   Patna        0.90  True
1  Rahul   22     72   Delhi        0.72  True
2  Priya   20     95  Mumbai        0.95  True
3  Ankit   23     50   Patna        0.50  True
4   Sara   21     83   Delhi        0.83  True

**Sort the DataFrame by Marks in descending order.**

In [36]:
df.sort_values(by="Marks", ascending=False)

    Name  Age  Marks    City  Percentage  Pass
2  Priya   20     95  Mumbai        0.95  True
0    Avi   21     90   Patna        0.90  True
4   Sara   21     83   Delhi        0.83  True
1  Rahul   22     72   Delhi        0.72  True
3  Ankit   23     50   Patna        0.50  True

**Print the average marks.**

In [37]:
df["Marks"].mean()

np.float64(78.0)

**Print the student with the highest marks.**

In [45]:
df.iloc[df["Marks"].idxmax()]

Name           Priya
Age               20
Marks             95
City          Mumbai
Percentage      0.95
Pass            True
Name: 2, dtype: object

**Print the total number of students.**

In [47]:
df.shape[0]

5